### ISSUE TITLE
There is a mistake in your test vectors

### ISSUE THREAD

**Issue by ddeath** [input-output-hk/cardano-crypto#43]
Here:
https://github.com/input-output-hk/cardano-crypto/blob/master/tests/goldens/cardano/crypto/wallet/BIP39-128#L5

It looks that private key is not correct.

**Comment by ddeath** [comment]
Sorry, my bad. Copy paste mistake... Its indeed correct.

**Comment by erikd** [comment]
Glad to have other people's eyes on this anyway.
