### ISSUE TITLE
Some transactions don't end in blockchain

### ISSUE THREAD

**Issue by JayMaree** [input-output-hk/cardano-crypto#56]
| Release | Operating System       | Cause |
| ---     | ---                    | ---   |
| 2.0.1    | Ubuntu Bionic) | Code  v Configuration v Environment v Human v Unknown |

# Context
We run both `cardano-wallet` and `cardano-explorer` on one Ubuntu server. We execute API calls against the wallet to generate new transactions. A few transactions (on daily basis) won't end up in the Blockchain.
Transaction has been generated but stays at:
```
"confirmations": 0,
```

We do pay enough fee and we do have enough funds. I used cli-command `curl -X GET http://localhost:8090/api/v1/transactions?id={{txid}} | jq .
` to get the json response which contains the 0 confirmations line.
 

# Steps to Reproduce

1. Executed a new order with the same amount and it'll pass

## Expected behavior

The transaction will end up in the Cardano Blockchain
## Actual behavior
The confirmations stays at zero.
<A clear and concise description of what you observe instead. If applicable add screenshots to help explain your problem.>

---

# Resolution Plan

# PR

| Number   | Base      |
| ---      | ---       |
| #?       | `develop` |

# QA

**Comment by NicolasDP** [comment]
Thanks for reporting the issue. This is however the wrong repository. There is nothing here related to the issue you are describing. You could try cardano-sl.
