### ISSUE TITLE
HD version bytes for BIP-0032

### ISSUE THREAD

**Issue by eosfomogame** [input-output-hk/cardano-crypto#58]
Hello guys, where can I find these BIP32 data (xpriv, xpub) for Cardano (yoroi wallet)
```
bitcoin: {
    messagePrefix: '\x18Bitcoin Signed Message:\n',
    bech32: 'bc',
    bip32: {
      public: 0x0488b21e,
      private: 0x0488ade4
    },
    pubKeyHash: 0x00,
    scriptHash: 0x05,
    wif: 0x80
  }
```
https://github.com/satoshilabs/slips/blob/master/slip-0132.md
https://cardanolaunch.com/assets/Ed25519_BIP.pdf
https://bitcoin.stackexchange.com/questions/28380/i-want-to-generate-a-bip32-version-number-for-namecoin-and-other-altcoins
Thanks

**Comment by vincenthz** [comment]
while similar in spirit (same hierarchy), it doesn't use value available to the bip32 spec, so it cannot be express in term fo BIP32 data.
