### ISSUE TITLE
Adapt to Cardano and implement EIP-3267 (crypto salaries)

### ISSUE THREAD

**Issue by vporton** [input-output-hk/cardano-crypto#74]
Adapt to Cardano and implement https://eips.ethereum.org/EIPS/eip-3267

It is, by the way, good for the claimed purpose to support science.

**Comment by erikd** [comment]
That EIP has nothing to do with cryptography which is what this repo implements.

Supporting science is a separate issue which is probably better served by [Prject Catalyst](https://iohk.io/en/blog/posts/2020/09/16/project-catalyst-introducing-our-first-public-fund-for-cardano-community-innovation/).
