### ISSUE TITLE
About wallet_encrypted_derive_private in encrypted_sign.c

### ISSUE THREAD

**Issue by soooneee** [input-output-hk/cardano-crypto#78]
Hi, I have a question about implementation of `wallet_encrypted_derive_private()` in `encrypted_sign.c`.
https://github.com/input-output-hk/cardano-crypto/blob/04c211d7f9504b04eb6595cab62eb39a573467f1/cbits/encrypted_sign.c#L308-L360

As fas as I know, your code is the implementation of [slip-0023](https://github.com/satoshilabs/slips/blob/master/slip-0023.md). Child key derivation of slip0023 follows BIP32-Ed25519 ([ieee](https://ieeexplore.ieee.org/document/7966967), [google docs](https://drive.google.com/file/d/0ByMtMw2hul0EMFJuNnZORDR2NDA/view?resourcekey=0-5yJh8wV--HB7ve2NuqfQ6A)) that have a condition of discarding child "if kL is divisible by the base order n". 
But I can't find them in the method. I want to know whether the condition is exist or not.

**Comment by vincenthz** [comment]
Hi @soooneee, the condition "kL is divisible by the base order n" cannot actually happen, this is why the check is not performed as this is always mathematically false.
